# Generated by Django 4.2.5 on 2023-10-17 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cagliaritour", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_date", models.DateField()),
                ("departure_time", models.CharField(max_length=5)),
                (
                    "moving_preference",
                    models.CharField(
                        choices=[
                            ("car", "Car"),
                            ("bus", "Bus"),
                            ("train", "Train"),
                            ("plane", "Plane"),
                            ("bike", "Bike"),
                            ("walking", "Walking"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "main_interests",
                    models.CharField(
                        choices=[
                            ("nature", "Nature and Outdoor Activities"),
                            ("culture", "Cultural Experiences"),
                            ("adventure", "Adventure Sports"),
                            ("food", "Food and Culinary"),
                            ("history", "Historical Sites"),
                            ("shopping", "Shopping"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TravelPreferenceForm",
            fields=[
                (
                    "travelpreference_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cagliaritour.travelpreference",
                    ),
                ),
            ],
            bases=("cagliaritour.travelpreference",),
        ),
    ]
