# Generated by Django 4.2.5 on 2023-10-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cagliaritour", "0002_travelpreference_travelpreferenceform"),
    ]

    operations = [
        migrations.AddField(
            model_name="locations",
            name="icon_image",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="TravelPreferenceForm",
        ),
    ]
