# Generated by Django 4.2.5 on 2023-10-31 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cagliaritour", "0003_locations_icon_image_delete_travelpreferenceform"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locations",
            old_name="adress",
            new_name="address",
        ),
        migrations.RemoveField(
            model_name="locations",
            name="club",
        ),
    ]
