# Generated by Django 4.2.5 on 2024-01-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cagliaritour", "0004_rename_adress_locations_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locations",
            name="OpeningTime",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="locations",
            name="accessibility",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="locations",
            name="animals",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="locations",
            name="category",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="locations",
            name="description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="locations",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/images/"),
        ),
        migrations.AddField(
            model_name="locations",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="locations",
            name="toilet",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="locations",
            name="visitTime",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="locations",
            name="website_address",
            field=models.URLField(blank=True, null=True),
        ),
    ]
