# Generated by Django 4.2.5 on 2024-03-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cagliaritour", "0005_locations_openingtime_locations_accessibility_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Category", models.CharField(max_length=100)),
                ("Description", models.TextField()),
                ("OpeningTime", models.CharField(max_length=100)),
                ("Website", models.URLField(blank=True, null=True)),
                ("PhoneNumber", models.CharField(blank=True, max_length=20, null=True)),
                ("Location", models.CharField(max_length=100)),
                ("Address", models.CharField(max_length=255)),
                ("Toilet", models.BooleanField(default=False)),
                ("Accessibility", models.BooleanField(default=False)),
                ("Animals", models.BooleanField(default=False)),
                (
                    "Image",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/images/"
                    ),
                ),
                (
                    "Icon",
                    models.ImageField(blank=True, null=True, upload_to="static/icons/"),
                ),
                ("VisitTime", models.CharField(max_length=100)),
                ("Map_Priority", models.IntegerField(default=0)),
            ],
        ),
    ]
