# Generated by Django 4.2.5 on 2024-03-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cagliaritour", "0006_place"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Place",
        ),
    ]
