# Generated by Django 4.2.5 on 2024-03-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cagliaritour", "0007_delete_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Category", models.CharField(max_length=100)),
                ("Description", models.TextField()),
                ("OpeningTime", models.CharField(max_length=100)),
                ("Website", models.URLField(blank=True, null=True)),
                ("PhoneNumber", models.CharField(blank=True, max_length=20, null=True)),
                ("Location", models.CharField(max_length=100)),
                ("Address", models.CharField(max_length=255)),
                ("Toilet", models.BooleanField(default=False)),
                ("Accessibility", models.BooleanField(default=False)),
                ("Animals", models.BooleanField(default=False)),
                ("Image", models.CharField(blank=True, max_length=250, null=True)),
                ("Icon", models.CharField(blank=True, max_length=250, null=True)),
                ("VisitTime", models.CharField(max_length=100)),
                ("Map_Priority", models.IntegerField(default=0)),
            ],
        ),
    ]
