# Generated by Django 4.2.5 on 2024-03-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cagliaritour", "0010_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="place_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
