# Generated by Django 4.2.13 on 2024-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cagliaritour', '0011_place_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='OpeningTime',
            field=models.CharField(max_length=500),
        ),
    ]
