# Generated by Django 4.2.5 on 2024-07-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cagliaritour", "0011_place_place_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="locations",
            name="average_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="locations",
            name="num_negative_comments",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="locations",
            name="num_positive_comments",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="locations",
            name="user_rating_accessibility",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="locations",
            name="wheelchair_accessible_entrance",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="OpeningTime",
            field=models.CharField(max_length=500),
        ),
    ]
