# Generated by Django 4.2.5 on 2024-10-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cagliaritour", "0012_locations_average_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="average_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="num_negative_comments",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="num_positive_comments",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="user_rating_accessibility",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="wheelchair_accessible_entrance",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
