# Generated by Django 4.2.5 on 2024-10-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cagliaritour",
            "0013_place_average_rating_place_num_negative_comments_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="QValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("nationality", models.CharField(max_length=50)),
                ("interests", models.JSONField()),
                ("action", models.JSONField()),
                ("q_value", models.FloatField(default=0)),
            ],
            options={
                "unique_together": {("age", "nationality", "interests", "action")},
            },
        ),
    ]
