# Generated by Django 4.2.5 on 2024-11-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cagliaritour", "0014_qvalue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="ID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),

        migrations.AlterField(
            model_name="place",
            name="VisitTime",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="place",
            name="num_negative_comments",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="place",
            name="num_positive_comments",
            field=models.IntegerField(default=0),
        ),
    ]
